DROP TABLE IF EXISTS pins CASCADE;
CREATE TABLE pins(
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  topic_id INTEGER REFERENCES topics(id) ON DELETE CASCAdE,
  title VARCHAR(60) NOT NULL,
  url VARCHAR(255) NOT NULL,
  description TEXT,
  media VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  UNIQUE(user_id, url)
);
