DROP TABLE IF EXISTS favourites CASCADE;
CREATE TABLE favourites(
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  pin_id INTEGER NOT NULL REFERENCES pins(id) ON DELETE CASCADE,
  is_liked BOOLEAN NOT NULL DEFAULT FALSE,
  UNIQUE(user_id, pin_id)
);
