DROP TABLE IF EXISTS comments CASCADE;
CREATE TABLE comments(
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  pin_id INTEGER REFERENCES pins(id) ON DELETE CASCADE,
  comment_body TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);
