DROP TABLE IF EXISTS comments CASCADE;
CREATE TABLE comments(
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  pin_id INTEGER NOT NULL REFERENCES pins(id) ON DELETE CASCADE,
  comment_body TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);
