GRANT ALL PRIVILEGES ON TABLE users TO labber;
GRANT ALL PRIVILEGES ON TABLE topics TO labber;
GRANT ALL PRIVILEGES ON TABLE pins TO labber;
GRANT ALL PRIVILEGES ON TABLE ratings TO labber;
GRANT ALL PRIVILEGES ON TABLE favourites TO labber;
GRANT ALL PRIVILEGES ON TABLE comments TO labber;
GRANT USAGE ON SEQUENCE users_id_seq TO labber;
GRANT USAGE ON SEQUENCE topics_id_seq TO labber;
GRANT USAGE ON SEQUENCE pins_id_seq TO labber;
GRANT USAGE ON SEQUENCE ratings_id_seq TO labber;
GRANT USAGE ON SEQUENCE favourites_id_seq TO labber;
GRANT USAGE ON SEQUENCE comments_id_seq TO labber;
