GRANT ALL PRIVILEGES ON TABLE users TO labber;
GRANT ALL PRIVILEGES ON TABLE topics TO labber;
GRANT ALL PRIVILEGES ON TABLE pins TO labber;
GRANT ALL PRIVILEGES ON TABLE ratings TO labber;
GRANT ALL PRIVILEGES ON TABLE favourites TO labber;
GRANT ALL PRIVILEGES ON TABLE comments TO labber;
